Sprint-7-solution
elbonreedZ/java-kanban pull request #2
Opened 2024-04-13 23:19 UTC by elbonreedZ

Добавила FileBackedTaskManager

2024-04-15 17:41 UTC, YazykovMikhail requested changes

2024-04-15 17:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/FileBackedTaskManager.java
> +public class FileBackedTaskManager extends InMemoryTaskManager implements TaskManager {
От интерфейса не нужно, наследуйся только от класса,  ведь InMemoryTaskManager и так реализовывает интерфейс, плюс тебе не нужно переопределять все методы из интерфйеса, а только те которые влияют на состояние задач

2024-04-15 17:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/javacourse/russkina/schedule/task/Task.java
>      public String toString() {
Не стоит использовать классический toStroing для бизнес целей, не зря в задании подсказывает что нужно сделать свой. 
Ведь классический toString много где используется самой джавой, а тут получается мы ег опеределываем под требования бизнес процессов
Сделай отдельный метод

2024-04-15 17:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/FileBackedTaskManager.java
> +
Напрмер вот так может выглядить общий метод toString 
```
	public static String toString(Task task) {
		return task.getId() + "," + task.getType() + "," + task.getName() + "," + task.getStatus() + "," + task.getDescription() + "," + (task.getType().equals(TaskType.SUBTASK) ? task.getEpicId() : "");
	}
```

2024-04-15 17:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/InMemoryTaskManager.java
> +    protected final Map<Integer, Epic> epics = new HashMap<>();
Молодец

2024-04-15 17:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/FileBackedTaskManager.java
> +                fileWriter.write("id,type,name,status,description,epic\n");
Так же вынеси в класс CSVTaskFormat
например вот так:
	public static String getHeader() {
		return "id,type,name,status,description,epic";
	}
Так же обратви внимание, что перенос строки не является частью заголовка, это отдельаня сущность ,которую стоит использовать отдельно

2024-04-15 17:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/FileBackedTaskManager.java
> +        } catch (ManagerSaveException e) {
Эта обратботка не нужна, иначе в предыдущей не было смысло, можно сразу было выводить в консоль. 
Выбрасывать исклбчение - это и есть главная цель ,сохранить не удалось, дальше продолжить работать нельзя

2024-04-15 17:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/FileBackedTaskManager.java
> +            try (Writer fileWriter = new FileWriter(file)) {
Используй буферизацию для экономии ресурсов:
		try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {

2024-04-15 17:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/FileBackedTaskManager.java
> +                    fileWriter.write(epic.toString() + "\n");
Перенос строк делай отдельынм методом:
		writer.newLine();
Ведь в каждой операционно системе свой перенос строки

2024-04-15 17:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/FileBackedTaskManager.java
> +    private Task fromString(String value) {
не зря же ты делала ТипЗадач
	public static Task taskFromString(String value) {
		final String[] values = value.split(",");
		final int id = Integer.parseInt(values[0]);
		final TaskType type = TaskType.valueOf(values[1]);
		final String name = values[2];
		final TaskStatus status = TaskStatus.valueOf(values[3]);
		final String description = values[4];
		if (type == TaskType.TASK) {
			return new Task(id, name, description, status);
		}
		if (type == TaskType.SUBTASK) {
			final int epicId = Integer.parseInt(values[5]);
			return new Subtask(id, name, description, status, epicId);
		}
//		type == TaskType.EPIC
		return new Epic(id, name, description, status);
	}

2024-04-15 17:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/Types.java
> +package ru.yandex.javacourse.russkina.schedule.manager;
Перенеси в папку task

2024-04-15 17:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/Types.java
> +public enum Types {
Type классы называются в единсвенно числе и когда поле будет использоваться оно будет означать только один тип

2024-04-15 17:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/javacourse/russkina/schedule/task/Task.java
Стоит в задачи добавить или поле Type type;
или просто метод:

```
	public TaskType getType() {
		return TaskType.TASK;
	}
```
Который будет однозначно идентифицировать каждую из задач

2024-04-15 17:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/FileBackedTaskManager.java
> +
Все методы которые ниже этого комментария и вот этот еще: private Task fromString(String value) {
вынеси в класс CSVTaskFormat - это будет утилиьныц класс для работы с csv
Как раз от туда будут вызываться статические методы как и положено для утилитного класса

2024-04-15 17:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/FileBackedTaskManager.java
> +    public static FileBackedTaskManager loadFromFile(File file) throws IOException {
Обрабатывай ошибку, не пробрасывай, 
Обрабатывай и выбраси свое исключение, которое будет говорить о чем случитлось

2024-04-15 17:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/FileBackedTaskManager.java
> +        }
Нужно так же востановить счетчик идентификаторов, ведь программа должна продолжить работать. 
Просто при считывании задачи находи самый максимальный идентификатор, он и будет точкой отсчета для дальнейшей работы

2024-04-15 22:00 UTC, elbonreedZ commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/FileBackedTaskManager.java
> +public class FileBackedTaskManager extends InMemoryTaskManager implements TaskManager {
Я задавалась вопросом этим)) А методы я и так только нужные переопределяла

2024-04-15 22:02 UTC, elbonreedZ commented on src/main/java/ru/yandex/javacourse/russkina/schedule/task/Task.java
>      public String toString() {
и над этим тоже думала, но если спрашивать, то у всех мнения разделялись

2024-04-15 22:33 UTC, elbonreedZ commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/FileBackedTaskManager.java
> +
Не работает получение айди эпика без приведения типов

2024-04-15 22:39 UTC, elbonreedZ commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/FileBackedTaskManager.java
> +        }
у меня он уже восстанавливается в методе restoreTaskToManager 
if (task.getId() > super.getTaskIdCounter()) {
            super.setTaskIdCounter(task.getId());
        }

2024-04-16 04:49 UTC, YazykovMikhail approved these changes

2024-04-16 11:50 UTC, merged