Sprint 8 solution time and duration
elbonreedZ/java-kanban pull request #3
Opened 2024-04-27 00:16 UTC by elbonreedZ

2024-04-27 18:14 UTC, YazykovMikhail requested changes

2024-04-27 18:14 UTC, YazykovMikhail commented on src/main/java/ru/yandex/javacourse/russkina/schedule/task/Epic.java
> +    private List<Integer> subtasksId;
сначала обьявляются поля, потом методы

2024-04-27 18:14 UTC, YazykovMikhail commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/InMemoryTaskManager.java
> +            return null;
Сделай свое исключение:
TaskValidationException
и выбрасывай его тут с опсианием, что задача пересекается

2024-04-27 18:14 UTC, YazykovMikhail commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/InMemoryTaskManager.java
> +    public Set<Task> getPrioritizedTasks() {
просто:
	public List<Task> getPrioritizedTasks() {
		return new ArrayList<>(prioritizedTasks.values());
	}

ведь они уже у тебя лежат в отсортированном порядке

2024-04-27 18:14 UTC, YazykovMikhail commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/InMemoryTaskManager.java
> +    protected final Set<Task> sortedTasks = new TreeSet<>((t1, t2) -> {
лучше назвать
prioritizedTasks
лучше называть не что с ними делается, а почему.

2024-04-27 18:14 UTC, YazykovMikhail commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/InMemoryTaskManager.java
> +    private void setEpicDurationAndTime(int epicId) {
updateEpicDuration - будет получше название, по анлогии с updateEpicStatus



и сделай отдельно еще метод :
```
	protected void updateEpic(int epicId) {
		Epic epic = epics.get(epicId);
		updateEpicStatus(epic);
		updateEpicDuration(epic);
	}
```
Что бы теперь его вызывать везде, где вызываются два этих метода. Вместо двух методов, будет один

2024-04-27 18:14 UTC, YazykovMikhail commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/InMemoryTaskManager.java
> +            return null;
а что бы описание было максимально полезным, стоит еще писать с какой задачей пересекается, но в этом случае стоит выбрасывать исключение в самом методе, например вот так:
```

	private void prioritize(Task task) {
		final LocalDateTime startTime = task.getStartTime();
		final LocalDateTime endTime = task.getEndTime();
		for (Task t : prioritizedTasks) {
			final LocalDateTime existStart = t.getStartTime();
			final LocalDateTime existEnd = t.getEndTime();
			if (!endTime.isAfter(existStart)) {// newTimeEnd <= existTimeStart
				continue;
			}
			if (!existEnd.isAfter(startTime)) {// existTimeEnd <= newTimeStart
				continue;
			}

			throw new TaskValidationException("Задача пересекаются с id=" + t.getId() + " c " + existStart + " по " + existEnd);
		}

		prioritizedTasks.add(task);
	}
```

2024-04-27 19:01 UTC, elbonreedZ commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/InMemoryTaskManager.java
> +    public Set<Task> getPrioritizedTasks() {
Но мне же нужно их сначала добавить, их количество может меняться, к тому же убрать все задачи, у которых пустые значения старт тайм

2024-04-27 19:44 UTC, elbonreedZ commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/InMemoryTaskManager.java
> +            return null;
не могу понять, что за метод. Если который проверяет пересечения, то он должен быть булеан, и он никак не связан с логикой приоритета, просто по сету приоритетных задач легче двигаться, я выполню задание с исключением, но по-своему

2024-04-28 05:55 UTC, YazykovMikhail requested changes

2024-04-28 05:55 UTC, YazykovMikhail commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/InMemoryTaskManager.java
> +        } catch (TaskValidationException e) {
Обрабатывать не нужно, в этом и смсл выбрасывать исключение, это тоже самое что вернуть true/false, если исключение выбрасилось, все процесс отсановился и вернулся ответ об конкретной ошибке которую ты описала в исключении. 
если делаешь true false, то исключение не нужно. 
но возвращать null в таком случае эт оне очень.

2024-04-28 05:55 UTC, YazykovMikhail commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/InMemoryTaskManager.java
> +    public Set<Task> getPrioritizedTasks() {
Я немного пропустил этот моммент. Добавление задача в prioritizedTasks должно происходит в момент добаления/обновления задач, если времени для добавления нет, то как раз выбрасывается исключпние/не добавляется задача

2024-04-28 05:55 UTC, YazykovMikhail commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/InMemoryTaskManager.java
> +    public Set<Task> getPrioritizedTasks() {
Поэтому тут просто:
return new ArrayList<>(prioritizedTasks.values());
}
а добавлени/проверка в prioritizedTasks должна проходит в соответсвущих методах. add/update

Представляешь что каждый раз когда ызвается метод getPrioritizedTasks будут сортироваться все задачи и доабвлятсья в список. А вызываться он будет часто, потому что бы отобразить на фронте последовательность задач, нужно его вызывать, т.е при каждом обновлении страницы каждого пользователя. 

И в текущей реализации поле prioritizedTasks - вообще не нужна получается, т.е весь процесс сортировки делает этот метод и делает это каждый.  
А prioritizedTasks создвался как раз для этого, что бы он сортировал/хранил задачи.

2024-04-28 05:55 UTC, YazykovMikhail commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/InMemoryTaskManager.java
> +    private boolean isTasksOverlapStream(Task newTask) {
т.е вот как в твоем случае будет выглдяеть этот метод:

```
  private void addPrioritized(Task newTask) {
        if (newTask.getStartTime() == null) {
            throw new TaskValidationException(
                    "Задача не может быть добавлена/обновлена, отсутсвует времяни старта");
        }
        Optional<Task> crossedTask = getPrioritizedTasks().stream()
                .filter(task -> !task.getType().equals(Type.EPIC))
                .filter(task -> task.getId() != newTask.getId())
                .filter(streamTask -> isTasksOverlap(newTask, streamTask))
                .findFirst();
        if (crossedTask.isPresent()) {
            throw new TaskValidationException(
                    "Задача не может быть добавлена/обновлена, она пересекается с id = " + crossedTask.get().getId()
                            + ", время начала: " + crossedTask.get().getStartTime() +
                            ", время окончания: " + crossedTask.get().getEndTime()
            );
        }

        prioritizedTasks.add(newTask);
    }
```

2024-04-28 05:55 UTC, YazykovMikhail commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/InMemoryTaskManager.java
>      public Task createTask(Task task) {
И вот так создавние
   public Task createTask(Task task) {
        task.setId(generateTaskId());
        Task finalTask = new Task(task.getName(), task.getDescription(), task.getId(), task.getStatus(),
                task.getDuration(), task.getStartTime());
        addPrioritized(finalTask);
        tasks.put(finalTask.getId(), finalTask);
        return finalTask;
    }

2024-04-28 05:55 UTC, YazykovMikhail commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/InMemoryTaskManager.java
>      public Task createTask(Task task) {
поменяй везде

2024-04-28 05:55 UTC, YazykovMikhail commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/InMemoryTaskManager.java
> +    protected void updateEpic(int epicId) {
старайся избегать дублирования, даже самого минимального. 
у тебя сйечас в каждом из этих методов получается задача, идет двойной поиск по одной и той же задаче, стоит сделать вот так:
```

 Epic epic = epics.get(epicId);
  updateEpicStatus(epic);
  updateEpicDurationAndTime(epic);
```
  
 В методах не получать эпик, а принимать его уже в аргументах. и получсается мы ищем задача 1 раз в хранилище, вместо 2.

2024-04-28 06:00 UTC, YazykovMikhail requested changes

2024-04-28 06:00 UTC, YazykovMikhail commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/TaskValidationException.java
> +package ru.yandex.javacourse.russkina.schedule.manager;
вынеси в папку exception

2024-04-28 13:21 UTC, elbonreedZ commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/InMemoryTaskManager.java
> +    private boolean isTasksOverlapStream(Task newTask) {
Задача может быть добвлена и обновлена если отсутствует время старта, но не в приоритетные задачи, а в мапы

2024-04-28 13:49 UTC, elbonreedZ commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/InMemoryTaskManager.java
> +    private boolean isTasksOverlapStream(Task newTask) {
и эпики получаются будут отсутствовать в приоритетных задачах?

2024-04-28 14:06 UTC, elbonreedZ commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/InMemoryTaskManager.java
>      public Task createTask(Task task) {
а где обработка исключения? или так и должно быть, что на этом программа прерывается?

2024-04-28 19:22 UTC, YazykovMikhail commented
Тесты прошли, работу я принимаю, молодец, а в бизнес процессах можно долго капаться и идеализировать.

2024-04-28 19:22 UTC, YazykovMikhail approved these changes

2024-04-28 19:22 UTC, YazykovMikhail commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/InMemoryTaskManager.java
>      public Task createTask(Task task) {
Так и должно быть, программа прерывается сейчас, дальше программа будет работать на сервере и не будет завершаться, просто будет возвращаться иключение

2024-04-28 19:22 UTC, YazykovMikhail commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/InMemoryTaskManager.java
> +    private boolean isTasksOverlapStream(Task newTask) {
Вообще в реальм мире, эпике не отслеживаются, Ведь эпик это то что общее, например:
Построить дом - это пик
и теперь пошли его подзачи(сабтаски):
1) Сдлеать фундамент 
2) Поставить стены
3) купить мебель
Вот как раз они и не должно пересекаться, все должно идти последовательно. 

И отедльн оесть задача(Task)
Посадить дерево, - это не связано со строительством дома, поэтому это просто задача, но они тоде не должна пересекаться по времени иначе как одновременно класть стены и сажать дерево.

2024-04-28 20:48 UTC, elbonreedZ commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/InMemoryTaskManager.java
> +    private boolean isTasksOverlapStream(Task newTask) {
спасибо за подробный ответ!

2024-04-28 20:50 UTC, merged

2024-04-28 20:57 UTC, elbonreedZ commented on src/main/java/ru/yandex/javacourse/russkina/schedule/manager/InMemoryTaskManager.java
> +    private boolean isTasksOverlapStream(Task newTask) {
Только остался вопрос, по задачам и подзадачам где не указано время. Получается таких сделать нельзя, и можно убрать конструкторы без времени?